version: 2

jobs:
  build:
    docker:
      - image: ubuntu:zesty
    steps:
      - run: apt-get update
      - run: apt-get -y install build-essential
      - run: wget https://github.com/LoopPerfect/buckaroo/releases/download/v1.3.1/buckaroo_1.3.1_amd64.deb
      - run: sudo dpkg -i buckaroo_1.3.0_all.deb
      - run: buckaroo resolve
      - run: buck run :test
